-- 1. Total Sales and Revenue Analysis

-- Total Revenue:

SELECT SUM(total) AS TotalRevenue
FROM dw_schema.invoice_details;

-- Insight: Understand overall revenue generated by the business.

-- Average Order Value (AOV):

SELECT AVG(total) AS AverageOrderValue
FROM dw_schema.invoice_details;

-- Insight: Helps gauge the average spending per transaction.

-- Sales Trend Over Time:

SELECT DATE_TRUNC('month', invoice_date) AS Month, SUM(total) AS MonthlyRevenue
FROM dw_schema.invoice_details
GROUP BY Month
ORDER BY Month;

-- Insight: Identify monthly revenue trends for seasonal analysis.

-- 2. Customer Insights

-- Top 5 Customers by Revenue:

SELECT c.first_name, c.last_name, SUM(id.total) AS TotalRevenue
FROM dw_schema.invoice_details id
JOIN dw_schema.customer c ON id.customer_id = c.customer_id
GROUP BY c.first_name, c.last_name
ORDER BY TotalRevenue DESC LIMIT 5;

-- Insight: Identify high-value customers for targeted campaigns.

-- Customer Distribution by Country:

SELECT billing_country, COUNT(DISTINCT customer_id) AS CustomerCount
FROM dw_schema.invoice_details
GROUP BY billing_country
ORDER BY CustomerCount DESC;

-- Insight: Helps identify key regions contributing to customer base growth.

-- 3. Product Performance

-- Top 5 Selling Tracks:

SELECT t.name, COUNT(id.invoice_line_id) AS TotalSales
FROM dw_schema.invoice_details id
JOIN dw_schema.track t ON id.track_id = t.track_id
GROUP BY t.name
ORDER BY TotalSales DESC LIMIT 5;

-- Insight: Identify the most popular music tracks driving sales.

-- Top Genres by Sales:

SELECT t.genre_name, COUNT(id.track_id) AS TracksSold
FROM dw_schema.invoice_details id
JOIN dw_schema.track t ON id.track_id = t.track_id
GROUP BY t.genre_name
ORDER BY TracksSold DESC;

-- Insight: Understand which music genres are performing best in sales.

-- Top Artists by Revenue:

SELECT a.artist_name, SUM(id.total) AS TotalRevenue
FROM dw_schema.invoice_details id
JOIN dw_schema.track t ON id.track_id = t.track_id
JOIN dw_schema.album_details a ON t.album_id = a.album_id
GROUP BY a.artist_name
ORDER BY TotalRevenue DESC LIMIT 5;

-- Insight: Helps determine the most profitable artists for promotional opportunities.

-- 4. Operational Efficiency

-- Sales Performance by Media Type:

SELECT t.media_type_name, SUM(id.total) AS TotalRevenue
FROM dw_schema.invoice_details id
JOIN dw_schema.track t ON id.track_id = t.track_id
GROUP BY t.media_type_name
ORDER BY TotalRevenue DESC;

-- Insight: Compare sales across different media formats for strategic planning.
